### ISSUE TITLE
Using shared libraries within CDK app

### ISSUE THREAD

**Issue by Mikoz93** [adrian-goe/nx-aws-cdk-v2#176]
Hi @adrian-goe, thanks for this awesome plugin!

I'm trying to use a shared library that was generated by the NX workspace plugin within the CDK app but I'm unable to deploy the app due to a 'MODULE_NOT_FOUND' error that's produced when running the `deploy` command.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/16376504/188273256-eeb47e7c-56ec-4928-aac4-8ffed4a68aae.png">

This is the AppStack that's generated by default:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/16376504/188273138-3935e721-e4c6-45cd-bf7e-bcf1050eee94.png">

As you can see, TypeScript detects the shared module without issues due to the configured `paths` in `tsconfig.base.json` at the root of the workspace directory.

Have you ever encountered anything like this, and if so, do you recommend any solutions?

**Comment by adrian-goe** [comment]
Hi, thanks 😊

I haven't had this issue before. So I don't have an idea in my mind. Unfortunately I'm also unable to check this until next weekend.
But if you can't solve this issue until then, I will look into it! Have a nice day

**Comment by Mikoz93** [comment]
Thanks, I'll try and investigate!

**Comment by Mikoz93** [comment]
Found a fix. It's seems like the below needs to be added to the `tsconfig.base.json` located at the root of the workspace directory:

```
"ts-node": {
    "require": ["tsconfig-paths/register"]
}
```
This requires `tsconfig-paths` package to be installed as well.

Reference: https://stackoverflow.com/a/72622089
